### ISSUE TITLE
Is there a list of EDL repositories?

### ISSUE THREAD

**Issue by AshitakaLax** [rdp/sensible-cinema#22]
Hi @rdp, I'm up in Logan, and caught word of this tool. I'm wondering if you have any list of repositories that host EDL's. 
I'm using Kodi, and would like to figure out how I could integrate this into my home media server.

Awesome thanks

**Comment by rdp** [comment]
EDL's for files? Unfortunately I'm not aware of any :(

**Comment by AshitakaLax** [comment]
k I'm hoping to create a tool that will auto generate them, based on subtitles combined with voice recognition tools. this would only be a partial support for specific words to be muted.

I guess my goal would be to have a kodi app that would link to repos that would pull latest, and filter them.

thanks for the quick response.

**Comment by misbach** [comment]
@AshitakaLax I'm in Kaysville :-). Does Kodi support EDL files, or are you trying to implement that feature? I've been wanting to spin up a website to host EDL files for years. The problem is people don't have the media players to use them, and users don't know how to create EDLs.

**Comment by arrietaeguren** [comment]
Hi @rdp, @AshitakaLax and @misbach I'm currently working on a project to host EDL files :)

My idea is to build an open source EDL repository where everyone can access basic metadata and EDL information about popular movies. It currently support searching by _title_, _imdb code_ and _opensubtitles hash_. And returns basic metadata as poster, actors, pgCode, imdb rating... It also handles is a pretty basic way EDL versioning and contribution privileges.

The EDL information is not there yet, but I'm planning to populate it automatically (by parsing subtitles) and with user contributions...

You can have a look at it at https://github.com/fcinema/api. That's just a first approach, I'm happy to include any other field/functionality so that more projects can fit in (the more, the merrier ^_^).

So, what fields/functionalities do you think the API should have?

**Comment by rdp** [comment]
Some way to "resync" it to different files would be nice.  Good luck, I
will say the best way to get started is to somehow create a huge library of
edits, it isn't easy! :)

**Comment by arrietaeguren** [comment]
Thanks for the feedback and the quick response!

Generating the library is not going to be a one day job, but if the different apps work well and we all share the same database, I think we can do it.

About the syncing (that's really good question :-), after testing different methods (subtitles, average frame luminosity, getting the user to sync manually...) I think there are two solutions: subtitles and [perceptual hashing](https://en.wikipedia.org/wiki/Perceptual_hashing).

Subtitles are easy. Together with the EDL file, we distribute subtitles on sync with the file used to create the edits. If the viewer has access to a valid (on sync) subtitle file we perform a simple correlation between subtitles and infer the time difference...

The perceptual hashing is my favorite (precise down to the frame and doesn't need subtitles :).  On the reference video, we capture some frames, compute their hash and store the hash-time pair in the EDL file. On the users video, we extract some hashes and correlate... Unlike cryptographic hashing, perceptual hashing outputs similar hashes for similar images. In my tests I was able to identify (almost) uniquely the corresponding frame on different (distorted) files.

Both systems are compatible, so we can store both information's on the database and let each app decide which system to use.

Oh! and obviously, once a specific file/streaming provider has been synced, we can store the "time offset"-"file/provider ID" pair and use it for future references!!

What do you think? (sorry for the super long text)

Codes implementing [subtitle](https://github.com/fcinema/standalone-intf/blob/master/main.qml) and [hash](https://github.com/fcinema/desktop-app/blob/develop/app/views/netflix.html) based synchronization.

**Comment by misbach** [comment]
@arrietaeguren Well done! I'm very excited about your project. We've needed this for a long time. I think the crowds will come and built out a great database of EDL files. This is the only way to stop the movie industry from shutting everyone down. Great job!
