### ISSUE TITLE
Confusion about how Play It My Way detects ads

### ISSUE THREAD

**Issue by jacob-willden** [rdp/sensible-cinema#28]
Thanks again for creating this amazing program! Play It My Way has been a such a great filtering solution for when I watch Amazon and Youtube. I also greatly appreciate that you have released the program into the open-source world for other developers to learn from. 

I have a question regarding one of the functions in the source code for the extension, linked below:

https://github.com/rdp/sensible-cinema/blob/9a6b021e7fb24b39517d07ac9fdbca1c049c4a05/html5_javascript/chrome_extension/edited_generic_player.js#L1103

Basically, I'm trying to figure how this function detects when an ad is playing on Amazon Video. It appears the extension can determine if an ad is playing by determining if the video element's duration is different from `current_json.url.total_time` by more than 10.5 seconds, and if the later variable is greater than 0 (and if `current_json` isn't null). Upon further investigation, I found out that the `current_json` object gets its properties from the Kemal server hosted on the Play It My Way website.

So my question is: where does the server get the value for the `current_json.url.total_time` for the video on Amazon, so it can be compared with the video element's `duration` property?

Thank you in advance!

**Comment by rdp** [comment]
When it is first added to the system it gets added "from" the website
playing the movie.  So it reads the duration, then makes a request back to
the server "create an entry for this url, this title, this duration".  So
basically, at create time... You're brave to drive into the code! :)

On Monday, December 14, 2020, jacob-willden <notifications@github.com>
wrote:
> Thanks again for creating this amazing program! Play It My Way has been a
such a great filtering solution for when I watch Amazon and Youtube. I also
greatly appreciate that you have released the program into the open-source
world for other developers to learn from.
>
> I have a question regarding one of the functions in the source code for
the extension, linked below:
>
>
https://github.com/rdp/sensible-cinema/blob/9a6b021e7fb24b39517d07ac9fdbca1c049c4a05/html5_javascript/chrome_extension/edited_generic_player.js#L1103
>
> Basically, I'm trying to figure how this function detects when an ad is
playing on Amazon Video. It appears the extension can determine if an ad is
playing by determining if the video element's duration is different from
current_json.url.total_time by more than 10.5 seconds, and if the later
variable is greater than 0 (and if current_json isn't null). Upon further
investigation, I found out that the current_json object gets its properties
from the Kemal server hosted on the Play It My Way website.
>
> So my question is: where does the server get the value for the
current_json.url.total_time for the video on Amazon, so it can be compared
with the video element's duration property?
>
> Thank you in advance!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/I2_-p4aIEjSlpEQ85RZIQrLVfoajZ62dwOwpf3fq9m006m4F7UZ67pU5m82fm_V6pIxVjDw8NTccGVc17p6znP-pHQqrKcroUUXIcttaxDdIC-yxzXQaeYs5SA4llMIyGI_LvYhmZsTTVF5VtAlIIgCwPd2XckotLuNjb6o_bwy4HdzURJn_3gRVVAwUdxb3dbf5Nr0PuTb-rKGFfwVlLwBnofg=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUDOCZNGIVT75ALXJVDSU3ENTA5CNFSM4U3UXHIKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4LNZCU7Q.gif>

**Comment by jacob-willden** [comment]
> You're brave to drive into the code! :)

Thanks! It's been a great learning exercise. =D

> When it is first added to the system it gets added "from" the website
playing the movie.  So it reads the duration, then makes a request back to
the server "create an entry for this url, this title, this duration".  So
basically, at create time...

Cool! So `current_json.url.total_time` is the video element's `duration` when the video is first added to the system, and `!withinDelta(current_json.url.total_time, videoDuration(), 10.5)` is checking if the video duration stored in the system is more than 10.5 seconds longer or shorter than video element's `duration` right now (when playing the video with filters). And if that returns true (along with `current_json.url.total_time > 0`), that means an ad is playing. Is that all correct?

**Comment by rdp** [comment]
Yeah right on :)

On Wednesday, December 16, 2020, jacob-willden <notifications@github.com>
wrote:
> You're brave to drive into the code! :)
>
> Thanks! It's been a great learning exercise. =D
>
> When it is first added to the system it gets added "from" the website
> playing the movie. So it reads the duration, then makes a request back to
> the server "create an entry for this url, this title, this duration". So
> basically, at create time...
>
> Cool! So current_json.url.total_time is the video element's duration when
the video is first added to the system, and
!withinDelta(current_json.url.total_time, videoDuration(), 10.5) is
checking if the video duration stored in the system is more than 10.5
seconds longer or shorter than video element's duration right now (when
playing the video with filters). And if that returns true (along with
current_json.url.total_time > 0), that means an ad is playing. Is that all
correct?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/er4DXEjtucZlgspBX-cpBhZbQtALW4jgW5lMkolzR5DItchVUJY_8oWNZFEDAitVpsSQxCuMjoeCP2Ejmd3tBCAnPTXF5EwRo-Qp7BLQY7B5vYhlJjRdYqy8VwjxcFOpd74WP7ifYWM1--We-4FFBEofI6YkzqoxANTOKOnvJFWuHOPr0MfvVRsmC2WL7Wx8ZPcI3I8ToyhrAMg7WLMPb3k1zSavz8q07kNa4P_pMQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUCD2KPE4JS5B4PCFQDSVEZ2LA5CNFSM4U3UXHIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFSDZ3IQ.gif>

**Comment by jacob-willden** [comment]
Perfect! Thank you so much for the help!

**Comment by rdp** [comment]
It's pretty ugly, my apologies in advance...

**Comment by jacob-willden** [comment]
No problem! If it works, it works. :) Thanks again!
